live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "0x6e7681"
# blue = "0x79c0ff"
# cyan = "0x39c5cf"
# green = "0x79c0ff"
# magenta = "0xbc8cff"
# red = "0xffa198"
# white = "0xb1bac4"
# yellow = "0xe3b341"
#
# [colors.cursor]
# cursor = "0xc9d1d9"
# text = "0x0d1117"
#
# [colors.normal]
# black = "0x484f58"
# blue = "0x58a6ff"
# cyan = "0x39c5cf"
# green = "0x58a6ff"
# magenta = "0xbc8cff"
# red = "0xff7b72"
# white = "0xb1bac4"
# yellow = "0xd29922"
#
# [colors.primary]
# background = "0x0d1117"
# foreground = "0xc9d1d9"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x090618"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"


[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
unfocused_hollow = true


[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 12
y = 12
